# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98de6fa5de3e27a75133c6884164dba8c34f485937c89578d5795219500d4215efc0a989c328325f5a85c422d20e2bbafe5ae78e96dbcdf8e86f037cc9a39b9e

test:
  secret_key_base: 106b5835f94db1c4ad4813f581ab80df47b5431a0d39c66ffbb8796d00d7b3851851e30b5b32f67ae3572e7162ce5b047ac1cfa3d1fded2492118c261fea523b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
